#pragma config(Sensor, S1, TIR, sensorI2CCustom)
#pragma config(Motor,  motorA,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

//joystick settings
int threshold = 3; // jostick values under this will be ignored
int joy_left; //left joystick vals
int joy_right; //right joystick vals
int joy_dpad;
int joy_triangle;
int joy_x;

//i2c commands
ubyte pan_left = 0x01; // command to pan left 
ubyte pan_right = 0x02; // command to pan camera right 
byte toggle_blue = 0x03;
byte toggle_green = 0x04;


void sendCommand(ubyte command){
	ubyte msgSize = 0x04;
	ubyte deviceAddress = 0x14; //0x0A on Arduino
	ubyte regAddress = 0x01;

	ubyte i2cMsg[7];//create empty msge on stack
	i2cMsg[0] = msgSize;
	i2cMsg[1] = deviceAddress;
	i2cMsg[2] = regAddress;
  i2cMsg[3] = command;
  //unused 
  i2cMsg[4] = 0x00;
  i2cMsg[5] = 0x00;
  i2cMsg[6] = 0x00;

  sendI2CMsg(S1, &i2cMsg[0], 0x00); //send message 
}

void arduinoControl(){
		getJoystickSettings(joystick);
		joy_left = joystick.joy1_y1;
		joy_right = joystick.joy1_y2;
		joy_dpad = joystick.joy1_TopHat;
		joy_triangle = joy1Btn(4);
		joy_x = joy1Btn(2);
		if(joy_dpad == 6){
			sendCommand(pan_left);
			wait1Msec(50);
		}	
		else if(joy_dpad == 2){
			sendCommand(pan_right);
			wait1Msec(50);
		}
		else if(joy_triangle){
			sendCommand(toggle_green);
			wait1Msec(50);
		}	
		else if(joy_x){
			sendCommand(toggle_blue);
			wait1Msec(50);
		}	
}		

void locomotion(){
	getJoystickSettings(joystick);
	joy_left = joystick.joy1_y1;
	joy_right = joystick.joy1_y2;
	if(abs(joy_left) > threshold){
		motor[leftMotor] = joy_left;
	}	else{
		motor[leftMotor] = 0;
	}	
	if(abs(joy_right) > threshold){
		motor[rightMotor] = joy_right;
	} else{
		motor[rightMotor] = 0;
	}
	// arm control 
	if(nMotorEncoder[arm] < 170 && joy1Btn(Btn8)==1){
		motor[arm] = 25;
	} else if(nMotorEncoder[arm] > 0 && joy1Btn(Btn6)==1){
		motor[arm] = -25;
	} else{
		motor[arm] = 0;
	}
}
	

task main(){
	nMotorEncoder[arm] = 5;
	while(true){
		arduinoControl();
		locomotion();
	}
}
