#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

int threshold = 3; // jostick values under this will be ignored
int joy_left; //left joystick vals
int joy_right; //right joystick vals
task main()
{
	while(nNxtButtonPressed != kExitButton){
		getJoystickSettings(joystick);
		joy_left = joystick.joy1_y1;
		joy_right = joystick.joy1_y2;
		if(abs(joy_left) > threshold){
			motor[leftMotor] = joy_left;
		}	else{
			motor[leftMotor] = 0;
		}	
		if(abs(joy_right) > threshold){
			motor[rightMotor] = joy_right;
		} else{
			motor[rightMotor] = 0;
		}
	}	
}
